### ISSUE TITLE
Publishing function does not work when the project path is too long

### ISSUE THREAD

**Issue by MartinZikmund** [xamarin/XamarinAzureChallenge#11]
Because of filesystem path length problem, publishing from a folder which is too nested via Visual Studio will throw a nondescriptive error. I will update the challenge help text to note this.

**Comment by eincioch** [comment]
I, already managed to activate the challenge, I am waiting for the mail.

![capture20190924164326916](https://user-images.githubusercontent.com/12565944/65553966-d42f5d00-deed-11e9-894b-b8dd19ac66ac.png)
![capture20190924164640814](https://user-images.githubusercontent.com/12565944/65553967-d42f5d00-deed-11e9-8afe-9438bf837d0b.png)
![capture20190924164703931](https://user-images.githubusercontent.com/12565944/65553969-d42f5d00-deed-11e9-8dbc-f63d2f37d11f.png)

**Comment by brminnick** [comment]
Thanks @MartinZikmund for the update!

#14
