### ISSUE TITLE
something is missing here: Task 3: Configure the Xamarin App

### ISSUE THREAD

**Issue by eincioch** [xamarin/XamarinAzureChallenge#12]
Something is missing here

In task 3, before step 6, how to create the function is missing, here he went on to detail:

This was what I added

![capture20190924162847318](https://user-images.githubusercontent.com/12565944/65553763-3045b180-deed-11e9-9553-7af8042dc624.png)
![capture20190924162906490](https://user-images.githubusercontent.com/12565944/65553764-30de4800-deed-11e9-9da8-292f4747cf38.png)
![capture20190924162944209](https://user-images.githubusercontent.com/12565944/65553765-3176de80-deed-11e9-87e6-09e24cd3e1ea.png)

**Comment by brminnick** [comment]
We create the Function in [Task 1: Create an Azure Function resource in Azure](https://github.com/xamarin/XamarinAzureChallenge#task-1-create-an-azure-function-resource-in-azure).

To create the Azure Function and publish the code to it, we have the option to use [Visual Studio on PC](https://github.com/xamarin/XamarinAzureChallenge#2a-use-visual-studio-on-pc), [Visual Studio for Mac](https://github.com/xamarin/XamarinAzureChallenge#2b-use-visual-studio-for-mac) or the [Azure CLI](https://github.com/xamarin/XamarinAzureChallenge#2c-use-azure-cli)

**Comment by eincioch** [comment]
When I arrived at task 3, step 5, I didn't have the "SubmitChallengeFunction" function, that is why I did those steps.

And I managed to register.


![capture20190924173343735](https://user-images.githubusercontent.com/12565944/65555275-d2679880-def1-11e9-909b-112a30fcd819.png)

**Comment by eincioch** [comment]
And I loaded the project, and registered without problems.

![capture20190924164326916](https://user-images.githubusercontent.com/12565944/65555461-5de12980-def2-11e9-9d0f-30ee325e6344.png)
![capture20190924164640814](https://user-images.githubusercontent.com/12565944/65555462-5e79c000-def2-11e9-8909-dfc2501b6730.png)
![capture20190924164703931](https://user-images.githubusercontent.com/12565944/65555463-5e79c000-def2-11e9-96e3-b4de3c667846.png)

**Comment by brminnick** [comment]
Ah - good catch! I did not include this step in the [Visual Studio steps](https://github.com/xamarin/XamarinAzureChallenge#2a-use-visual-studio-on-pc)
![Publish to Azure](https://user-images.githubusercontent.com/13558917/65555679-24082700-dee2-11e9-9bcb-746b9f03470b.png)

**Comment by eincioch** [comment]
Sure, you have to post :), I did that later.

![capture20190924180446034](https://user-images.githubusercontent.com/12565944/65556540-874f8480-def5-11e9-9177-27efc8426169.png)

**Comment by eincioch** [comment]
Bueno, continuaré esperando que llegue el correo, porque ya me registré.

**Comment by eincioch** [comment]
Hello, yesterday I completed the challenge, and I still haven't received any confirmation email.

**Comment by brminnick** [comment]
Yes, we are working through an issue on our email server.

I can confirm we've received your submission and you have officially been entered into the competition.
