### ISSUE TITLE
Different number of main prizes

### ISSUE THREAD

**Issue by mkieres** [xamarin/XamarinAzureChallenge#15]
In the article on blog.xamarin.com it states that there will be 10 winners of the main prize (https://devblogs.microsoft.com/xamarin/xamarin-azure-functions-challenge/) whereas the GitHub readme says it will be only 6. Probably worth making sure these numbers are the same.

**Comment by brminnick** [comment]
Thanks @mkieres - good catch!

The blog post is correct: there will be 10 grand prize winners.

I've updated the Readme to match 👍
