### ISSUE TITLE
No email received

### ISSUE THREAD

**Issue by geekatwork** [xamarin/XamarinAzureChallenge#16]
I completed the challenge but yesterday but haven't received an email. Is there a delay or have I mucked up my email on the entry (xamarinazurechallenge@geekatwork.net)?

**Comment by brminnick** [comment]
Hi @geekatwork! We’re working through a problem with the email server, but I confirmed that we received your submission and that you’re good to go!

**Comment by seansparkman** [comment]
I also did no receive an email.  It was probably submitted about the same time.

**Comment by TechWatching** [comment]
Yes, same for me.
