### ISSUE TITLE
Email wrong 

### ISSUE THREAD

**Issue by patel-pragnesh** [xamarin/XamarinAzureChallenge#17]
in challenge submission if wrong email id enter then ? i am not get email from Microsoft. 
user can resubmit?

**Comment by brminnick** [comment]
Hi @patel-pragnesh! We've fixed the problems with our email server preventing the automated emails, and you should be receiving an email confirmation today.

I confirmed you successfully completed the competition.

If you haven't received an email confirmation by the end of today, shoot me an email and we'll get it sorted out: brandon@microsoft.com.
