### ISSUE TITLE
You're not eligible for an Azure free account

### ISSUE THREAD

**Issue by Shaboo** [xamarin/XamarinAzureChallenge#22]
Why am I getting this error?

I even tried to register for pay-as-you-go and It says i am not eligible also,

any idea why?

**Comment by brminnick** [comment]
Hi @Shaboo! Can you copy/paste the error message and include a screenshot of the webpage?

**Comment by Shaboo** [comment]
Hi @brminnick 

the error message is:

> You're not eligible for an Azure free account
> 
> Don't worry—you can still use Azure by paying as you go, with no upfront commitments. Cancel anytime.

![image](https://user-images.githubusercontent.com/5777450/66134333-c33bc580-e62a-11e9-8c14-557c147c014b.png)


thanks

**Comment by brminnick** [comment]
Have you created a free account previously? That’s typically what the error message means. 

Try it again using a different email address to sign up for Azure.

**Comment by Shaboo** [comment]
no I haven't,

I have tried to create one but get the same error (maybe one year ago).

it is okay, i will try with different email and different credit card, thanks

i will close this issue for now.
