### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by TheCodeTraveler** [xamarin/XamarinAzureChallenge#3]
![AFEndpoint1](https://user-images.githubusercontent.com/13558917/57551436-e97c6400-731d-11e9-8ac7-eb8ae884c69e.png)

![AFEndpoint2](https://user-images.githubusercontent.com/13558917/57551471-f8631680-731d-11e9-9e39-8b7f50f56534.png)
![binding](https://user-images.githubusercontent.com/13558917/57551696-8ccd7900-731e-11e9-9295-5e032bb15f72.png)

**Comment by brminnick** [comment]
![ApplicationSettings](https://user-images.githubusercontent.com/13558917/65477931-c241b180-de3c-11e9-9111-2fe516ef4a5a.png)

**Comment by brminnick** [comment]
![IdentityYes](https://user-images.githubusercontent.com/13558917/65478063-22d0ee80-de3d-11e9-9f8e-467e8d1e2113.png)

**Comment by brminnick** [comment]
<img width="532" alt="Screen Shot 2019-09-24 at 10 09 32 AM" src="https://user-images.githubusercontent.com/13558917/65533966-7b42d300-deb3-11e9-87bc-d0820f879ec5.png">

**Comment by brminnick** [comment]
![CloseAccountWindow](https://user-images.githubusercontent.com/13558917/65534155-c1983200-deb3-11e9-99de-b9e0b5049f75.png)

**Comment by brminnick** [comment]
![Close](https://user-images.githubusercontent.com/13558917/65535255-ea212b80-deb5-11e9-9748-6e646c032028.png)
![Sign In](https://user-images.githubusercontent.com/13558917/65535257-ea212b80-deb5-11e9-9ad6-a33bfea6b534.png)
![Add an account](https://user-images.githubusercontent.com/13558917/65535258-ea212b80-deb5-11e9-84a8-c2c722f6b64a.png)
![AccountSettings](https://user-images.githubusercontent.com/13558917/65535259-eab9c200-deb5-11e9-823c-17d4f49769bc.png)

**Comment by brminnick** [comment]
![PublishSucceeded](https://user-images.githubusercontent.com/13558917/65556072-3a62b280-dee3-11e9-982a-9e313b2ac34d.png)
![ViewOutput](https://user-images.githubusercontent.com/13558917/65556074-3afb4900-dee3-11e9-8b64-e41bf4e2a8f2.png)
