### ISSUE TITLE
Splash screen does not go away

### ISSUE THREAD

**Issue by indcoder** [xamarin/XamarinAzureChallenge#31]
When I try to build the Android project on the emulator , the below splash screen remains constant and does not go away

![image](https://user-images.githubusercontent.com/2099300/67426399-a2e2a380-f5f7-11e9-8fa3-c9ccdbe44ceb.png)

**Comment by brminnick** [comment]
You'll want to create an emulator with a higher-density pixel display.

That's not a splash screen; it is the first few characters of the Android status bar. Your emulator's display resolution is so low that it can only display a few characters.

**Comment by indcoder** [comment]
Thanks @brminnick I'm using the default emulator [Pixel 2 Pie 9.0] installed with VS 2019  

![image](https://user-images.githubusercontent.com/2099300/67427163-310b5980-f5f9-11e9-904b-a54bacc299b7.png)
