### ISSUE TITLE
Didn't Show Success Screen

### ISSUE THREAD

**Issue by zawhtut** [xamarin/XamarinAzureChallenge#32]
Hi... 
I wasn't shown "Challenge Completed!" screen.
Instead, I got "Oops! Created" 
and then I went back to edit submission...
I changed my email with the shorter email address.
then I received different response that my submission 
is completed with matching subscription id. As a matter of fact,
I mistakenly used the emails other than the email with Azure Subscription.
~ Zaw
![gitpub3](https://user-images.githubusercontent.com/10856644/67448089-d8bd6300-f5ca-11e9-88e8-70a4b63c2715.jpg) ![gitpub4](https://user-images.githubusercontent.com/10856644/67448088-d8bd6300-f5ca-11e9-91d6-28068191d990.jpg)

**Comment by zawhtut** [comment]
Actually... 
I received the email at 7:13 PM and went into spam folder since I submitted the challenge at 6:57 PM.
Anyhow Thanks for the challenge. 
I learned how to publish function app in Azure and connect with the Xamarin App... 
I get to familiarize with the steps and the processes in Azure...

**Comment by Xonshiz** [comment]
Would suggest that you CLOSE this issue, since it's been resolved?
