### ISSUE TITLE
".Net developer winners" sending with an error "SenderNotAuthenticatedForGroup"

### ISSUE THREAD

**Issue by lHubertl** [xamarin/XamarinAzureChallenge#33]
Hi, due to [TermsAndConditions](https://github.com/xamarin/XamarinAzureChallenge/blob/master/TermsAndConditions.md) 12th item, to see winners list after October 23, I have to send an email with a specific subject: 

> 12. WINNERS LIST
> Send email to xamarin@microsoft.com with the subject line “.Net developer winners” within 30 days of October 23, 2019 to receive a list of winners that received a prize worth $25.00 or more.

I have used my outlook account which I have used to finish a challenge, to send an email for xamarin@microsoft.com and with a “.Net developer winners” subject line, with empty body content. But for a response, I received an error:

![image](https://user-images.githubusercontent.com/17310375/67576543-6de56680-f747-11e9-92c0-d48ae97831bd.png)

...

![image](https://user-images.githubusercontent.com/17310375/67576683-b00ea800-f747-11e9-92f3-6a7c194f82ea.png)

> Note
> I have to mention the information below because it may be caused an issue.
> I did some manipulation with an Alias previously my alias was revanmvs2@gmail.com, and I also have tried to change "From" email address to previous alias email, but it is still not working. Third alias was lhubertl@outlook.com

**Comment by Xonshiz** [comment]
This is nothing you can do about. Folks at Microsoft need to change their permissions for "xamarin@microsoft.com".
Maybe @brminnick or @codemillmatt could look into this?

**Comment by sphinxy** [comment]
It would be enough also just to publish winners list somewhere.

**Comment by codemillmatt** [comment]
@cmatskas - looks like the `xamarin@microsoft.com` alias is not working for a winner's list. Are you able to help out here?

**Comment by jphellemons** [comment]
Seems to be an configuration error in Office365 for that account. So we can't contact Microsoft about the winners unfortunately...

**Comment by Xonshiz** [comment]
Yeah, that's the issue in permissions of receiver's list of "Xamarin" DList. Why don't you just release the list of winners @codemillmatt ?

**Comment by mimunoz** [comment]
@brminnick any comment about this? Who won?

**Comment by cmatskas** [comment]
With regards to the winner list, we’re working on it this week and we will be announcing the winners at the end of the week. We will make the list available on this repo. Thanks everyone for your participation and for your patience

**Comment by brminnick** [comment]
Hi all! We have posted the winners list on the README. 

Thank you all again for participating in the challenge 🙌
