### ISSUE TITLE
Finished the challenge

### ISSUE THREAD

**Issue by ravinderjangra** [xamarin/XamarinAzureChallenge#6]
Finished the challenge. Do I have to raise a PR or something?

![Simulator Screen Shot - iPhone Xʀ - 2019-09-23 at 23 51 55](https://user-images.githubusercontent.com/9795917/65451706-5754a280-de5d-11e9-8fc6-5d5ecc9ce64b.png)

**Comment by ravinderjangra** [comment]
Hey @brminnick, do I have to submit any code or url or anything else for this?

**Comment by brminnick** [comment]
Great! That's all you need to do!

Keep an eye out for a confirmation email

**Comment by ravinderjangra** [comment]
Didn't recieve any email ☹️

**Comment by brminnick** [comment]
Hi @ravinderjangra!

We had some issues with our email server & the automated emails.

I checked the submissions and confirmed that you have successfully completed the challenge and have been registered for the prizes 👍
