### ISSUE TITLE
Cannot find Azure subscription

### ISSUE THREAD

**Issue by patel-pragnesh** [xamarin/XamarinAzureChallenge#8]
follow by your step in mac. 
we could not find any subscription in your account. 

VS 2019 in MAC

**Comment by brminnick** [comment]
Hi @patel-pragnesh!

You'll have to sign into your Azure Account in **Visual Studio** > **Account...**.

I'll add this to the walkthrough 👍 

![VisualStudioMacAccount](https://user-images.githubusercontent.com/13558917/65533492-94974f80-deb2-11e9-9ea1-045ec4b2aa0a.png)
![AddAccount](https://user-images.githubusercontent.com/13558917/65533509-9e20b780-deb2-11e9-888c-cffb8ef6c48b.png)
